### ISSUE TITLE
ArgumentError: does not respond to `read`.

### ISSUE THREAD

**Issue by tobidelius** [refile/refile-sequel#2]
Hi.

I'm trying this in a Rack app and have set:

``` ruby
Refile.cache = Refile::Backend::FileSystem.new('tmp')
Refile.store = Refile::Backend::FileSystem.new('tmp')
```

``` ruby
class User < Sequel::Model
  extend Refile::Sequel::Attachment
  attachment :avatar
end
```

and call `user.update(avatar: params['avatar'])` but I get `ArgumentError: does not respond to`read`.`.

```
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/refile-0.5.5/lib/refile/backend_macros.rb:25:in `block (3 levels) in verify_uploadable'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/refile-0.5.5/lib/refile/backend_macros.rb:23:in `each'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/refile-0.5.5/lib/refile/backend_macros.rb:23:in `block (2 levels) in verify_uploadable'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/refile-0.5.5/lib/refile/attacher.rb:89:in `cache!'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/refile-0.5.5/lib/refile/attacher.rb:72:in `set'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/refile-0.5.5/lib/refile/attachment.rb:58:in `block (2 levels) in attachment'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2128:in `block in set_restricted'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2125:in `each'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2125:in `set_restricted'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:2195:in `update_restricted'
/Users/sandelius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1690:in `update'
```

Any idea what's happening?

**Comment by janko** [comment]
I think this is due to the fact that I haven't updated this gem according to the latest version of Refile. I'm currently traveling for two months, but I will try to find time to fix it in the next two weeks. Please ping me if I forget :)

**Comment by tobidelius** [comment]
Ohh that was a fast response :) It's ok, take your time. Refile is almost the only "good" uploader gem that doesn't depend on active(support/model). Refreshing.

**Comment by tobidelius** [comment]
ohh it was racks tempfile that was nil in params. If I use `env['rack.tempfiles'][0]` it works. Weird. Every encountered this?

**Comment by janko** [comment]
I didn't know about `env['rack.tempfiles']`, but if the file was uploaded, then it's strange that it's nil. Maybe you should just make a special case when the file is nil, which depends on the framework you're using.

Yeah, the fact that Refile isn't dependent on ActiveSupport/ActiveModel is very refreshing. Even if when you don't use Rails, it's still difficult to avoid it, people especially depend on ActiveSupport without a good reason. That's one of the reasons I chose the Roda framework over Grape.

**Comment by janko** [comment]
I figured from what you said that a `nil` was causing this error, so I'll close this.
